# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Building
  continueOnError: false
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    workingDirectory: './src'

- task: NuGetCommand@2
  displayName: Packing
  continueOnError: false
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
    includeSymbols: true
    basePath: './src'

- task: NuGetCommand@2
  displayName: Pushing to Nuget.org
  continueOnError: false
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org CrawlerWave.LogTestHelper'